# Generated by Django 4.0 on 2022-01-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_subscribers_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='name',
            new_name='Имя',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='email',
            new_name='Почта',
        ),
    ]
