# Generated by Django 4.0 on 2022-01-11 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_rename_name_subscriber_имя_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='Почта',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='subscriber',
            old_name='Имя',
            new_name='name',
        ),
    ]
